# Generated by Django 4.2.7 on 2025-11-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spike', 'Mention Spike'), ('negative', 'Negative Sentiment'), ('trending', 'Trending Topic')], max_length=20)),
                ('message', models.TextField()),
                ('threshold_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('twitter', 'Twitter'), ('news', 'News'), ('blog', 'Blog')], max_length=20)),
                ('source_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.brand')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
